version: '0.1'

services:
  wedding-app:
    image: wedding-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CertPassword}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Database:Local=false
      - ConnectionString=${ConnectionString}
      - Email:Enabled=false
      - Email:Address=${EmailAddress}
      - Email:Password=${EmailPassword}
      - Email:SmtpClient=${EmailSmtpClient}
    ports:
      - 8000:80
      - 8001:443
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/

# docker run -d --name eloquent_montalcini --mount source=${USERPROFILE}/.aspnet/https,target=/https/