version: '0.1'

services:
  wedding-app:
    image: wedding-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 3000:3000
