GET https://localhost:5001/api/guest

###

POST https://localhost:8001/api/guest
content-type: application/json

{
    "name": "Anja Axelsson",
    "age": 30,
    "myPreferedLanguage": "swe",
    "closestTo": "Shanna",
    "hobbies": "tejp lakan",
    "relation": "lekplatsen",
    "email": "axelsson_1991@hotmail.com",
    "specialFood": "nej"
}

###

POST http://localhost:3000/api/guest
content-type: application/json

{
    "name": "Carl Axelsson",
    "age": 30,
    "myPreferedLanguage": "swe",
    "closestTo": "Shanna",
    "hobbies": "tejp lakan",
    "relation": "lekplatsen",
    "email": "axelsson_1991@hotmail.com",
    "specialFood": "nej"
}